import java.util.ArrayList;
import java.util.Scanner;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;

public class Main {

    public static void main(String[] args) throws Exception {

        // Array List that contains each AES key generated by the user 
        ArrayList<SecretKey> listOfAESKeys = new ArrayList<SecretKey>();

        // Array List that contains each Iv generated by the user used for AES encryption/decryption
        ArrayList<IvParameterSpec> listOfIv = new ArrayList<IvParameterSpec>();

        // Array List that contains each DES key generated by the user 
        ArrayList<SecretKey> listOfDESKeys = new ArrayList<SecretKey>();
        // Array List that contains each Key from the MyKeyProvider class generated by the user 
        ArrayList<MyKeyProvider> listOfMyKeys = new ArrayList<MyKeyProvider>();
        
         // Display the main menu interface 
        System.out.println();
        Scanner myScanner = new Scanner(System.in); // Create  a scanner object
        System.out.println("########################");
        System.out.println("Menu Interface");
        System.out.println("########################");
        System.out.println("Enter an option below:");
        System.out.println("i.e Enter 1, 2 or 3 ");
        System.out.println("to select an option");
        System.out.println("########################");
        System.out.println("1: Encrypt Text");
        System.out.println("2: Decrypt Text");
        System.out.println("3: Create Your Own Key");
        System.out.println("4: Quit");
        System.out.println("########################");
        System.out.print("Enter Here:");
        String userInput = myScanner.nextLine(); // Set the user input as a variable
        

        // Continue displaying the menu until the user selects option 4 (Quit)
        while(userInput != "4") 

        {
        // Determine which menu option the user selected
        switch(userInput){

            case "1": // Option 1: Encrypt Text 
            
            // Display encryption algorithm options to the user
            System.out.println("##################################################################");
            System.out.println("Please Enter What Encryption Algorithm You Want To Use");
            System.out.println("i.e: Entering Caesar Cipher will select option 1: Caesar Cipher");
             System.out.println("################################################################");
            System.out.println("1: Caesar Cipher");
            System.out.println("2: AES");
            System.out.println("3: DES");
            System.out.println("Enter Here: ");
             // Store the user's encryption algorithm choice
            String optionChosen = myScanner.nextLine();

            System.out.println();

            // User gets an option of 3 different algorithms to use for encryption 
            // 3 options based on security level they provide: WEAK (Caesar Cipher), MODERATE (DES) OR STRONG (AES)

            // Caesar Cipher encryption option (weak encryption)
            if (optionChosen.equalsIgnoreCase("Caesar Cipher")){

                // Display metadata about the Caesar Ciphe
                System.out.println();
                System.out.print("Created by:" + CaesarCipher.getCreatedBy()); 
                System.out.println();

                // Prompts User to enter a plaintext message
                System.out.println("Enter the message you want to encrypt:");
                // Scanner to store user's input
                String message = myScanner.nextLine();
                System.out.println();

                // Prompt user to enter the shift amount
                System.out.println("Enter Shift Amount:");
                // Scanner to store the shift amount 
                String shift = myScanner.nextLine();

                // Conver shift amount from String to Integer
                int shiftAmount = Integer.parseInt(shift);
                System.out.println();

                // Encrypt the message using the Caesar Cipher
                String result = CaesarCipher.encryptString(message, shiftAmount);
                // Print out the encrypted text 
                System.out.println("Encrypted Text:" + result);
                System.out.println();

                // AES encryption option (strong encryption)
                } else if (optionChosen.equalsIgnoreCase("AES")){
                
                // Display AES algorithm information
                System.out.println();
                System.out.println();
                System.out.println("Name: " + AES.getFullName());
                System.out.println("Mode: " + AES.getMode());
                System.out.println("Created By: " + AES.getCreatedBy());
                System.out.println("Year Created:" + AES.getYearCreated());

                // Generate a new random symmetric key for AES Encryption/Decryption
                SecretKey newKey = AESKeyProvider.generateKey();
                System.out.println();
                
                // Store the generated AES key for later decryption
                listOfAESKeys.add(newKey);

                // Generate a new IV for AES encryption
                IvParameterSpec newIvParam =  AESIVProvider.generateIv();

                // Store te newly generated Iv for later decryption
                listOfIv.add(newIvParam);

                // Prompt user to enter text to be encrypted using AES
                System.out.print("Please Enter Text To Be Encrypted:");
                userInput = myScanner.nextLine();

                // Encrypt the input text using AES 
                String result = AES.encrypt(userInput, newIvParam, newKey);

                // Display encrypted AES output 
                System.out.println();
                System.out.println("Encrypted Text (AES): ");
                System.out.println();
                System.out.println(result);
                System.out.println();
                
                // DES encryption option (moderate encryption) 
                // Note: DES is no longer deemed secure in industry as it can be broken by powerful tools nowadays
                // Used by threat actors
                } else if (optionChosen.equalsIgnoreCase("DES")){
                
                 // Display DES algorithm information
                System.out.println();
                System.out.println("Name: " + DES.getFullName());
                System.out.println("Mode: " + DES.getMode());
                System.out.println("Created By: " + DES.getCreatedBy());
                System.out.println("Year Created:" + DES.getYearCreated());

                // Generate a 56-bit DES secret key
                SecretKey newKey = DESKeyProvider.generateKey();

               // Store the generated DES key for later decryption
                listOfDESKeys.add(newKey);

                // Prompt user to enter text to be encrypted using AES
                System.out.print("Please Enter Text To Be Encrypted:");
                userInput = myScanner.nextLine();

                // Encrypt the input text using DES
                String result = DES.encrypt(userInput, newKey);

                // Display encrypted DES output 
                System.out.println();
                System.out.println("Encrypted Text (DES): ");
                System.out.println();
                System.out.println(result);
                System.out.println();
                    
                }
            

            break;

            
            case "2":  // Option 2: Decrypt Text

            // Display decryption options
            System.out.println();
            System.out.println("######################################################");
            System.out.println("Please Enter What Decryption Algorithm You Want To Use");
            System.out.println("######################################################");
            System.out.println("##################");
            System.out.println("1: Caesar Cipher");
            System.out.println("2: AES");
            System.out.println("3: DES");
            System.out.println("##################");
            System.out.println("Enter Here:");
            // Store decryption algorithm choice
            optionChosen = myScanner.nextLine();
            System.out.println();

            // Caesar Cipher decryption
            if(optionChosen.equalsIgnoreCase("Caesar Cipher") ){

                System.out.println("Enter the message you want to decrypt (Caesar Cipher): ");
                String messageToDecrypt = myScanner.nextLine();
                System.out.println();
                System.out.println("Enter Shift Amount:");
                String shift = myScanner.nextLine();
                int shiftAmount = Integer.parseInt(shift);
                System.out.println();

                 // Decrypt message using Caesar Cipher
                String decryptedMessage = CaesarCipher.decryptString(messageToDecrypt, shiftAmount);

                // Display decrypted output
                System.out.println();
                System.out.println("Message Decrypted (Caesar Cipher): ");
                System.out.print(decryptedMessage);
                System.out.println();
            
                // AES decryption
            } else if (optionChosen.equalsIgnoreCase("AES")){

                // Display AES algorithm information
                System.out.println();
                System.out.println("Name: " + AES.getFullName());
                System.out.println("Mode: " + AES.getMode());
                System.out.println("Created By: " + AES.getCreatedBy());
                System.out.println("Year Created:" + AES.getYearCreated());
                System.out.println();

                // Prompt user for encrypted text
                System.out.println("Enter the message you want to decrypt (AES)");
                String messageToDecrypt = myScanner.nextLine();
                System.out.println();

                // Retrieve the most recently generated AES key and IV
                SecretKey decryptionKey = listOfAESKeys.get(listOfAESKeys.size()-1);
                IvParameterSpec iv = listOfIv.get(listOfIv.size()-1);

                // Attempt AES decryption
                try {
                String decryptedMessage = AES.decrypt(messageToDecrypt, decryptionKey, iv);
                System.out.println();
                System.out.println("Decrypted Message (AES):");
                System.out.println(decryptedMessage);
                System.out.println();
                } catch (Exception e) {
                    System.out.println("AES Decryption Failed....");
                    System.out.println("NOTE: Decryption only works with most recently encrypted message");
                    System.out.println("");
                }
                
               // DES decryption 
            } else if(optionChosen.equalsIgnoreCase("DES")){

                 // Display DES algorithm information
                System.out.println();
                System.out.println("Name: " + DES.getFullName());
                System.out.println("Mode: " + DES.getMode());
                System.out.println("Created By: " + DES.getCreatedBy());
                System.out.println("Year Created:" + DES.getYearCreated());

                // Prompt user for encrypted text
                System.out.println("Enter the message you want to decrypt (DES)");
                String messageToDecrypt = myScanner.nextLine();
                System.out.println();

                // Retrieve the most recently generated DES key 
                SecretKey decryptionKey = listOfDESKeys.get(listOfDESKeys.size()-1);

                // Attempt DES decryption
                String decryptedMessage = DES.decrypt(messageToDecrypt, decryptionKey);

                // Attempt DES Decryption 
                try {
                
                System.out.println();
                System.out.println("Decrypted Message (DES):");
                System.out.println(decryptedMessage);
                System.out.println();
                } catch (Exception e) {
                    System.out.println("DES Decryption Failed....");
                    System.out.println("NOTE: Decryption only works with the most recently encrypted message");
                    System.out.println("");
                }

            }


            break;

            case "3":  // Option 3: Create or Retrieve a Custom Key

            // Display key management options
            System.out.println();
            System.out.println("##############################");
            System.out.println("1: Create My Own Key");
            System.out.println("2: I Already Have My Own Key");
            System.out.println("##############################");
            System.out.println("Enter Your Option:");

            // Capture key option input
            userInput = myScanner.nextLine();
            int userInputAsInt = Integer.parseInt(userInput);

            // Create a new custom key
            if(userInputAsInt == 1){
            
            // Creates an instance of the MyKeyProvider Class
            MyKeyProvider mySecretKey = new MyKeyProvider();
            
            // Function call to add personal information to the new secret key object
            MyKeyProvider.createKey(mySecretKey);
            
            // Add key to array list called listOfMyKeys
            listOfMyKeys.add(mySecretKey);

            // Retrieve an existing custom key
            } else if(userInputAsInt == 2){
            
                try {

                    // Setting myKey to the most recent key added to the array list - listOfMyKeys
                    MyKeyProvider myKey = listOfMyKeys.get(listOfMyKeys.size()-1);

                    // Calls Method That Finds All Info on the user's key after answering security questions 
                    MyKeyProvider.findMyKey(myKey);

            } catch (Exception e) {
                System.out.println();
                System.out.println("##############################################################");
                System.out.println("Exception found in finding key....");
                System.out.println("Note: Ensure you have created a key before trying to find it");
                System.out.println("Ensure you only enter credentials of the most recently creatred key");
                System.out.println("##############################################################");
                System.out.println();
            }
            
            
            } else {
                System.out.println("User entered an invalid option");
            }
            

            break;

            case "4": // Exit program

            System.out.println("User has chose to quit the application.....");
            System.out.println();
            return;

                       

            default:

            System.out.println();
            System.out.println("Incorrect input provided");

            break;
        }

        // Redisplay the main menu after each operation
        System.out.println();
        System.out.println("########################");
        System.out.println("Menu Interface");
        System.out.println("########################");
        System.out.println("Enter an option below:");
        System.out.println("i.e Enter 1, 2 or 3 ");
        System.out.println("to select an option");
        System.out.println("########################");
        System.out.println("1: Encrypt Text");
        System.out.println("2: Decrypt Text");
        System.out.println("3: Create Your Own Key");
        System.out.println("4: Quit");
        System.out.println("########################");
        System.out.print("Enter Here:");
        
        userInput = myScanner.nextLine();

        }
          
    }
  
}
